### ISSUE TITLE
windows app works android doesn't work.help??

### ISSUE THREAD

**Issue by hasanuc20** [cabbi/modbus_client_tcp#3] opened 2023-12-29 12:57 UTC
Hello, I am using the Modbus TCP library. It works fine on the computer. but I want to run it on my android device. I can't connect. Can you help?

**Comment by cabbi** [comment] 2023-12-29 16:32
Hi, 

I have it running on my Android device. Do you have `<uses-permission android:name="android.permission.INTERNET"/>` set in your AndroidManifest.xml?

**Comment by hasanuc20** [comment] 2023-12-29 16:57
Yes there is.  to gradle file.
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
<uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
I tried it this way. but I could not communicate at all. It works in
simulation, but when I install the apk on the phone it doesn't work.

29 Ara 2023 Cum 19:32 tarihinde cabbi ***@***.***> şunu yazdı:

**Comment by cabbi** [comment] 2023-12-29 17:40
You're right, the problem is the `discoverServer` method. 
In order to enable it please add this permission as well: **ACCESS_FINE_LOCATION**
(see here: [network_info_plus package](https://pub.dev/packages/network_info_plus))

**Comment by hasanuc20** [comment] 2023-12-29 18:47
Okay, I will try it soon. I have another question.  How can I show modbus
errors?  can you show me an example?

29 Ara 2023 Cum 20:40 tarihinde cabbi ***@***.***> şunu yazdı:

**Comment by cabbi** [comment] 2023-12-30 06:59
To get the modbus  response code you simply check the return value when sending a request
``` dart
  // Create the modbus client.
  var modbusClient = ModbusClientTcp(serverIp, unitId: 1);

  var req = batteryStatus.getWriteRequest(BatteryStatus.running);
  var res = await modbusClient.send(req);
  print(res.name);
```

Please close this issue If your problem is solved... and just put a like in [pub.dev](https://pub.dev/packages/modbus_client_tcp) if you find this package useful :)

**Comment by hasanuc20** [comment] 2024-01-02 06:57
Teşekkürler, işe yaradı.

cabbi ***@***.***>, 30 Ara 2023 Cmt, 09:59 tarihinde şunu
yazdı:

**Closed as completed** 2024-01-02 06:57 UTC
